services:
  db:
    image: postgres:16
    container_name: oi_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: order_inventory
    ports:
      - "5432:5432"
    volumes:
      - oi_pgdata:/var/lib/postgresql/data

volumes:
  oi_pgdata: